### ISSUE TITLE
[버그] No take-off sounds for all aircrafts

### ISSUE THREAD

**Issue by telk5093** [CoconutKR/KoreanAirlinersSet#6]
==========[버그내용]==========
There is no take-off sounds and plays default sound effect (i.e. sounds when tram starts) when an aircraft is taking-off
항공기가 이륙할 때 이륙 효과음이 없고 대신 기본 효과음 (전차 출발시 나는 효과음)이 나옴

==========[개선사항]==========
Need to set sound effect for all vehicles.
모든 차량에 사운드 이펙트 지정 필요.

Note: https://newgrf-specs.tt-wiki.net/wiki/NML:List_of_sound_effects

eg) property block에 아래 사운드 이펙트 삽입
``sound_effect: SOUND_TAKEOFF_JET;``

==========[KAS내용]==========
KAS 차량 이름 : All
도색 이름 : (미도색시 무시)

**Comment by CoconutKR** [comment]
감사합니다 :)
